### PR TITLE
Add cargo fmt to github actions

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by Aplet123** [comment]
Hey, I just wanted to know why you're forking hundreds of rust repos and adding `cargo fmt` to their CI. Also, how did you even find our repo.

**Comment by Atul9** [comment]
Hi @Aplet123 I am just trying to contribute to opensource. Can you please share why was this PR closed?

**Comment by Aplet123** [comment]
Hello, thank you for your pull request, however your pull request has failed Github's automatic unit testing so we are hesitant to accept it. Thank you for your understanding.

**Comment by tripulse** [comment]
@Atul9 ~~He's rude~~ :wink:

**Comment by Buam** [comment]
Very rude

**Comment by tripulse** [comment]
Yea, this rudeness should be demolished by Github staff.

**Comment by Aplet123** [comment]
@tripulse I see this is your first time interacting with our project. Thank you for choosing to follow the progress of Octane. However, I would request that you read our [contributing guidelines](https://github.com/OctaneWeb/Octane/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/OctaneWeb/Octane/blob/master/CODE_OF_CONDUCT.md) before posting. If you have an issue with our project, please open a new issue as dictated by our contributing guidelines, and ensure that you follow the code of conduct. If you have an issue with the maintainers of the project, you may talk to the people in private, as this repository is solely for the project and not for personal feuds. If you perceive any rudeness on our behalf, we apologize, as we only wish the best for our projects and our contributors.

At Octane, we take our Code of Conduct very seriously and we strive to be as welcoming as possible to differing opinions and external contributions. As a corollary, we are also strict towards trolling, personal attacks, and harassment. People should feel comfortable contributing to this repository and we should foster a caring community. If you continue acting this way, we may have to take action. Thank you and have a nice day.

**Comment by Atul9** [comment]
Hi @Aplet123 I can fix that unit testing & Github CI will pass. Can I open a PR for that?

**Comment by Aplet123** [comment]
@Atul9 Thank you for your continued support. If you wish to fix the unit testing, please continue this pull request and I will reopen it.

**Comment by Atul9** [comment]
@Aplet123 I have pushed the code to the same branch but is it becuase this PR is closed hence the new commit is not displayed?

**Comment by Aplet123** [comment]
Sorry, we've made many changes to our code between the time of this pull request and your previous commit. These changes have been lost in your commit, so I cannot merge it.

**Comment by Daksh14** [comment]
Hey, @Atul9 we have changed our branch from `master` to `release` and our default branch is now `develop` so we require you to push to that. Thanks a lot

**Comment by Atul9** [comment]
ok @Daksh14.
Regarding the failing build its an issue in rustfmt which is fixed on rust nightly but it not availabe on rust stable.
I will check if it can be fixed using rustfmt::skip OR when the rustfmt is update on stable, I will open a PR.

**Comment by Aplet123** [comment]
I have tried it locally on both nightly and stable, as well as tried it on rust's playground with both nightly and stable, and I cannot reproduce the error.

**Pull request closed without merging**
